import ethereumLogo from '../images/networkLogos/ethereum-logo.png';
import polygonLogo from '../images/networkLogos/polygon-logo.png';
import gnosisLogo from '../images/networkLogos/gnosis-logo.png';
import config from '../config';

export default {
  1: {
    label: 'Ethereum Mainnet',
    token: 'ETH',
    id: '0x1',
    rpcUrl: `https://mainnet.infura.io/v3/${config.api.infuraApiKey}`,
    blockExplorer: 'https://etherscan.io/tx/',
    logo: ethereumLogo,
    hide: false,
  },
  3: {
    label: 'Ropsten',
    token: 'ROP',
    id: '0x3',
    rpcUrl: `https://ropsten.infura.io/v3/${config.api.infuraApiKey}`,
    blockExplorer: 'https://ropsten.etherscan.io/tx/',
    logo: ethereumLogo,
    hide: false,
  },
  4: {
    label: 'Rinkeby',
    token: 'RIN',
    id: '0x4',
    rpcUrl: `https://rinkeby.infura.io/v3/${config.api.infuraApiKey}`,
    blockExplorer: 'https://rinkeby.etherscan.io/tx/',
    logo: ethereumLogo,
    hide: false,
  },
  5: {
    label: 'Goerli',
    token: 'GOR',
    id: '0x5',
    rpcUrl: `https://goerli.infura.io/v3/${config.api.infuraApiKey}`,
    blockExplorer: 'https://goerli.etherscan.io/tx/',
    logo: ethereumLogo,
    hide: false,
  },
  137: {
    label: 'Polygon',
    token: 'MATIC',
    id: '0x89',
    rpcUrl: `https://polygon-mainnet.infura.io/v3/${config.api.infuraApiKey}`,
    blockExplorer: 'https://polygonscan.com/tx/',
    logo: polygonLogo,
    hide: false,
  },
  100: {
    label: 'Gnosis Chain',
    token: 'xDai',
    id: '0x64',
    rpcUrl: 'https://rpc.gnosischain.com ',
    blockExplorer: 'https://blockscout.com/xdai/mainnet/',
    logo: gnosisLogo,
    hide: false,
  },
  80001: {
    label: 'Polygon Mumbai',
    token: 'TEST-MATIC',
    id: '0x13881',
    rpcUrl: 'https://matic-mumbai.chainstacklabs.com',
    blockExplorer: 'https://mumbai.polygonscan.com/',
    logo: polygonLogo,
    hide: true,
  },
  1337: {
    label: 'Ganache',
    token: 'LOCAL',
    id: '0x1691',
    rpcUrl: 'http://localhost:7545',
    logo: ethereumLogo,
    hide: true,
  },
  31337: {
    label: 'Hardhat',
    token: 'TEST-ETH',
    id: '0x7a69',
    rpcUrl: 'http://localhost:8545',
    logo: ethereumLogo,
    hide: true,
  },
};
